### Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [7]:
import numpy as np

arr = np.random.randint(1,20,(5,5))
print(arr)

arr[::,2:3:] = 1

print(arr)

arr2 = np.random.randint(1,16,(4,4))
np.fill_diagonal(arr2,0)
print(arr2)

[[12  8 18  8  9]
 [ 5  7  2  4 14]
 [ 7 10  1 10 15]
 [ 1  3  7 13 19]
 [18 17  4  8  1]]
[[12  8  1  8  9]
 [ 5  7  1  4 14]
 [ 7 10  1 10 15]
 [ 1  3  1 13 19]
 [18 17  1  8  1]]
[[ 0  3  8  5]
 [15  0 10 13]
 [15 13  0 10]
 [13  2  6  0]]


### Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [28]:
arr3 = np.random.randint(1, 36, (6,6))

sub_array = arr3[2:5:,1:4:]

print(arr3)
print(sub_array)


arr4 = np.random.randint(1, 50, (5,5))

print(arr4)

border = np.concatenate((arr4[0,],arr4[::,0],arr4[-1,],arr4[::,-1]))
border_elements = np.unique(border)
print(border_elements)

[[21 14 10  7 33  3]
 [ 6 17 25 23 25 17]
 [14 24  4 20  1  4]
 [30 28  8 28 28 25]
 [25 14 10 25 12  7]
 [21  6  9 30  2 20]]
[[24  4 20]
 [28  8 28]
 [14 10 25]]
[[32  4 17  1 37]
 [48  3 19 49 15]
 [16 38 24 47 22]
 [18 26 48 15 16]
 [49  9 21 33  4]]
[ 1  4  9 15 16 17 18 21 22 32 33 37 48 49]


### Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [35]:
array = np.random.randint(1,100,(3,4))
array2 = np.random.randint(1,100,(3,4))

array_add = array + array2
array_sub = array - array2
array_mult = array * array2
array_div = array / array2

# print(array)
# print(array2)
print(array_add)
print(array_sub)
print(array_mult)
print(array_div)

array3 = np.random.randint(1,16,(4,4))

print(array3)

for i in range(4):
    print(f"sum of elements in row {i}: {np.sum(array3[i,])}")
    
for i in range(4):
    print(f"sum of elements in column {i}: {np.sum(array3[::,i])}")

#Alternative way:
row_sum = np.sum(array3,axis=1)
col_sum = np.sum(array3,axis=0)\
    
print(row_sum,col_sum)

[[ 50 132 103 142]
 [ 49 119 104  70]
 [ 94  36 116  93]]
[[-34  -4 -77  34]
 [  3  41 -30  20]
 [ 82 -34  -6 -71]]
[[ 336 4352 1170 4752]
 [ 598 3120 2479 1125]
 [ 528   35 3355  902]]
[[ 0.19047619  0.94117647  0.14444444  1.62962963]
 [ 1.13043478  2.05128205  0.55223881  1.8       ]
 [14.66666667  0.02857143  0.90163934  0.13414634]]
[[ 4  1  9 13]
 [ 8  1  4  6]
 [10 14  3  3]
 [ 9  4 11 11]]
sum of elements in row 0: 27
sum of elements in row 1: 19
sum of elements in row 2: 30
sum of elements in row 3: 35
sum of elements in column 0: 31
sum of elements in column 1: 20
sum of elements in column 2: 27
sum of elements in column 3: 33
[27 19 30 35] [31 20 27 33]


### Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [37]:
print(arr4)

mean = np.mean(arr4)
median = np.median(arr4)
stand = np.std(arr4)
variance = np.var(arr4)

print(mean,median,stand,variance)

[[32  4 17  1 37]
 [48  3 19 49 15]
 [16 38 24 47 22]
 [18 26 48 15 16]
 [49  9 21 33  4]]
24.44 21.0 15.294652660325438 233.9264


### Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [53]:
three = np.random.randint(1,6,(3,3))
one = np.random.randint(1,6,3)
# one = np.array([1,2,3])
print(one)
print(three)
print(three+one)

arr2 = np.random.randint(1,16,(4,4))
one2 = np.random.randint(1,6,(4,))

one2_col = one2.reshape(4,1)
print(arr2)
print(one2_col)
print(arr2-one2)
# print(np.concatenate((arr2,one2),axis=0))


[1 4 5]
[[5 1 1]
 [2 5 2]
 [1 1 2]]
[[6 5 6]
 [3 9 7]
 [2 5 7]]
[[ 5 10  9  6]
 [ 4  7  8 15]
 [14  4  6  5]
 [ 3 14  3 13]]
[[1]
 [5]
 [4]
 [3]]
[[ 4  5  5  3]
 [ 3  2  4 12]
 [13 -1  2  2]
 [ 2  9 -1 10]]


### Linear Algebra

1. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [56]:
array = np.random.randint(1,10,(2,3))
array2 = np.random.randint(1,10,(3,2))

matrix_mult = np.dot(array,array2)

print(matrix_mult)

[[63 79]
 [46 54]]


### Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [58]:
array = np.random.randint(1,9,(3,3))
print(array)
array = array.reshape(1,9)
print(array)
array = array.reshape(9,1)
print(array)

n_array = np.random.randint(1,100,(5,5))
print(n_array)
n_array = n_array.flatten()
print(n_array)
n_array = n_array.reshape(5,5)
print(n_array)



[[5 2 1]
 [8 4 5]
 [6 3 6]]
[[5 2 1 8 4 5 6 3 6]]
[[5]
 [2]
 [1]
 [8]
 [4]
 [5]
 [6]
 [3]
 [6]]
[[67 74 16 76 20]
 [79  9 24 48 14]
 [85 74 57 66 84]
 [43 88 53 47 61]
 [50 61 55 95 81]]
[67 74 16 76 20 79  9 24 48 14 85 74 57 66 84 43 88 53 47 61 50 61 55 95
 81]
[[67 74 16 76 20]
 [79  9 24 48 14]
 [85 74 57 66 84]
 [43 88 53 47 61]
 [50 61 55 95 81]]


### **Boolean Indexing**

1. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [61]:
array = np.random.randint(1,20,(4,4))

print(array)

print(np.where(array>10,10,array))

[[13 19 14  4]
 [ 1  6  9  8]
 [ 7 13 19 19]
 [ 3 11  1  2]]
[[10 10 10  4]
 [ 1  6  9  8]
 [ 7 10 10 10]
 [ 3 10  1  2]]
