1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [1]:
import numpy as np
one_D = np.array([2,3,4,5,6,7,8,9]) #1D array

two_D = np.array([[2,3,4,5],
                 [6,7,8,9]]) #2D array
three_D = np.array([[[2,3,4,5],
                    [6,7,8,9] ],
                   [[2,3,4,5],
                    [6,7,8,9] ]]) #3D array

#Dimensions
print(one_D.ndim)
print(two_D.ndim)
print(three_D.ndim)

#Shapes
print(one_D.shape)
print(two_D.shape)
print(three_D.shape)

#Size
print(one_D.size)
print(two_D.size)
print(three_D.size)

#Type
print(one_D.dtype)
print(two_D.dtype)
print(three_D.dtype)

1
2
3
(8,)
(2, 4)
(2, 2, 4)
8
8
16
int64
int64
int64


2 . Create:
- an array of zeros of shape (3,3)

- an array of ones of shape (2,5)

- an array filled with 7

In [50]:
zero = np.zeros(shape=(3,3))
one = np.ones(shape=(2,5))

array1 = np.full_like(a=one_D, fill_value=7)
array2 = np.full_like(a=two_D, fill_value=7)
array3 = np.full_like(a=three_D, fill_value=7)


print(zero)
print(one)
print(array1)
print(array2)
print(array3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[7 7 7 7 7 7 7 7]
[[7 7 7 7]
 [7 7 7 7]]
[[[7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]]]


3 . Create an array of even numbers between 10 and 50 using arange.

In [24]:
#using arange
even_num = np.arange(10,51,2)

#using linspace
even_num1 = np.linspace(10,50,21) #Divisions = ((50-10)/2)+1

# using logspace
ten_to_fifty = np.logspace(10,50,base=10)

print(even_num)
print(even_num1)
print(ten_to_fifty)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 42. 44.
 46. 48. 50.]
[1.00000000e+10 6.55128557e+10 4.29193426e+11 2.81176870e+12
 1.84206997e+13 1.20679264e+14 7.90604321e+14 5.17947468e+15
 3.39322177e+16 2.22299648e+17 1.45634848e+18 9.54095476e+18
 6.25055193e+19 4.09491506e+20 2.68269580e+21 1.75751062e+22
 1.15139540e+23 7.54312006e+23 4.94171336e+24 3.23745754e+25
 2.12095089e+26 1.38949549e+27 9.10298178e+27 5.96362332e+28
 3.90693994e+29 2.55954792e+30 1.67683294e+31 1.09854114e+32
 7.19685673e+32 4.71486636e+33 3.08884360e+34 2.02358965e+35
 1.32571137e+36 8.68511374e+36 5.68986603e+37 3.72759372e+38
 2.44205309e+39 1.59985872e+40 1.04811313e+41 6.86648845e+41
 4.49843267e+42 2.94705170e+43 1.93069773e+44 1.26485522e+45
 8.28642773e+45 5.42867544e+46 3.55648031e+47 2.32995181e+48
 1.52641797e+49 1.00000000e+50]


4 . Create a 4×4 matrix from 0–15. Then , extract:
- the first row

- the last column

- a 2×2 subarray from the center

In [31]:
mat = np.random.randint(0,15,(4,4))
print(mat)

first_row = mat[:1:,::]
print(first_row)

last_column = mat[::,3:4:]
print(last_column)

sub_array = mat[1:3:,1:3:]
print(sub_array)

[[ 3  9  2  9]
 [ 8 14  9 10]
 [ 1  2  8  4]
 [ 1 14  5  4]]
[[3 9 2 9]]
[[ 9]
 [10]
 [ 4]
 [ 4]]
[[14  9]
 [ 2  8]]


5 . Add a 1D array [1,2,3] to each row of a 3×3 matrix.

In [45]:
threexthree = np.random.randint(1,100,(3,3))
one_array = np.array([1,2,3])

add_row =  threexthree+one_array

print(threexthree)
print(one_array)
print(add_row)

[[64 30  5]
 [34 95  3]
 [90 12 36]]
[1 2 3]
[[65 32  8]
 [35 97  6]
 [91 14 39]]


6 . Given two arrays A and B, compute:
- (A + B) / 2
- A* *2 + B**2

In [54]:
A = np.random.randint(1, 50, size=(3, 4))
B = np.random.randint(51, 100, size=(3, 4))

print((A+B)/2)

print(A**2 + B**2)

[[66.5 42.5 44.5 46. ]
 [49.  40.  37.  63.5]
 [51.  34.  62.5 46. ]]
[[10957  4913  5065  7594]
 [ 4874  5000  3250 10445]
 [ 9074  2890  8653  5032]]
