In [20]:
import numpy as np

def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
    
    a = np.array(a)
    b = np.array(b)

    if a.shape[1] == b.shape[0]:
        result = np.dot(a,b)
        return result.tolist()
    else:
        return -1
        
    
print(matrix_dot_vector([[1, 2], [2, 4], [6, 8], [12, 4]], [1, 2, 3]))
print(matrix_dot_vector(a = [[1, 2], [2, 4]], b = [1, 2]))

-1
[5, 10]


## Extra

In [22]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b.shape)
print(np.sin(np.pi/2))

(2, 3)
1.0


In [24]:
a =np.array([3,1,2])
b =np.array([4,5,6])
print(a+b)
print(np.sort(a))

[7 6 8]
[1 2 3]


In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

np.dot(A,B)

array([[19, 22],
       [43, 50]])