## Part 1

In [10]:
import numpy as np

score = np.random.randint(0,100,10)
print("Highest Score:",score.max())
print("Lowest Score:",score.min())
print("Average Score:",score.mean())

Highest Score: 91
Lowest Score: 41
Average Score: 60.4


In [12]:
arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

arr_more50 = arr[arr>50]
sorted_arr = np.sort(arr)
index = np.argmax(arr)

print(arr_more50,sorted_arr,index)

[60 55 90 75] [30 40 45 50 55 60 75 90] 4


In [18]:
temp = np.random.randint(20,40,(4,4))
print(temp)
avg = temp.mean(axis=1)
print(avg)
highest_t = temp.max()
print(highest_t)
temp[temp>35] = 35
print(temp)

[[28 34 29 35]
 [24 33 37 32]
 [34 36 37 32]
 [36 38 37 23]]
[31.5  31.5  34.75 33.5 ]
38
[[28 34 29 35]
 [24 33 35 32]
 [34 35 35 32]
 [35 35 35 23]]


In [22]:
car_rec = np.random.randint(0,50,(3,5))
print(car_rec)

intersect = car_rec.sum(axis=0)
car_per_time = car_rec.sum(axis=1)

print("Total car per intersection: ",intersect,"\nTotal car per time slot:",car_per_time)

[[27 19 44 23 41]
 [20 13 19 42 26]
 [45 39 49 32 41]]
Total car per intersection:  [ 92  71 112  97 108] 
Total car per time slot: [154 120 206]


In [24]:
stock = np.array([12, 15, 9, 20, 18])

remain = stock - stock*(10/100)

print(remain)

[10.8 13.5  8.1 18.  16.2]


## Part 2

In [27]:
import pandas as pd   
data = {    'Name': ['Rahim', 'Karim', 'Selina', 'Babul', 'Mitu'],    
            'Math': [88, 75, 95, 60, 80],    
            'English': [78, 85, 90, 70, 88],    
            'Science': [92, 70, 85, 65, 90]  } 
df = pd.DataFrame(data)
df

Name  Math  English  Science
0   Rahim    88       78       92
1   Karim    75       85       70
2  Selina    95       90       85
3   Babul    60       70       65
4    Mitu    80       88       90

In [30]:

print("First row:")
df.iloc[0]

First row:


Name       Rahim
Math          88
English       78
Science       92
Name: 0, dtype: object

In [32]:
df.columns

Index(['Name', 'Math', 'English', 'Science'], dtype='object')

In [33]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [35]:
data = {  'Product': ['Phone', 'Laptop', 'Tablet', 'Monitor', 'Mouse'],  
          'Price': [700, 1200, 300, 250, 50],    
          'Units_Sold': [10, 5, 8, 6, 20]  } 
df = pd.DataFrame(data)

df

Product  Price  Units_Sold
0    Phone    700          10
1   Laptop   1200           5
2   Tablet    300           8
3  Monitor    250           6
4    Mouse     50          20

In [37]:
df[['Product','Price']]

Product  Price
0    Phone    700
1   Laptop   1200
2   Tablet    300
3  Monitor    250
4    Mouse     50

In [39]:
print(df.loc[2])
print()
print(df.iloc[2])

Product       Tablet
Price            300
Units_Sold         8
Name: 2, dtype: object

Product       Tablet
Price            300
Units_Sold         8
Name: 2, dtype: object


In [40]:
df['Revenue']= df['Price'] * df['Units_Sold']
df

Product  Price  Units_Sold  Revenue
0    Phone    700          10     7000
1   Laptop   1200           5     6000
2   Tablet    300           8     2400
3  Monitor    250           6     1500
4    Mouse     50          20     1000

In [42]:
df.sort_values(["Revenue"],ascending=False).head(3)

Product  Price  Units_Sold  Revenue
0   Phone    700          10     7000
1  Laptop   1200           5     6000
2  Tablet    300           8     2400

In [47]:
data = {    'Student': ['Amin', 'Tina', 'Rafi', 'Nadia', 'Sabbir'],    
            'Days_Present': [20, 18, 22, 15, 25],    
            'Days_Absent': [2, 4, 1, 7, 0]  }  
df = pd.DataFrame(data)
df

Student  Days_Present  Days_Absent
0    Amin            20            2
1    Tina            18            4
2    Rafi            22            1
3   Nadia            15            7
4  Sabbir            25            0

In [48]:
df.set_index("Student",inplace=True)
df

Days_Present  Days_Absent
Student                           
Amin               20            2
Tina               18            4
Rafi               22            1
Nadia              15            7
Sabbir             25            0

In [52]:
df.drop('Days_Absent',axis=1,inplace=True)
df

Days_Present
Student              
Amin               20
Tina               18
Rafi               22
Nadia              15
Sabbir             25

In [65]:
data = {    'Name': ['Rafiq', 'Nadia', 'Tuhin', 'Rima', 'Faruk'],    'Department': ['HR', 'IT', 'IT', 'Sales', 'Sales'],    'Salary': [40000, 55000, 52000, 45000, 47000],    'Experience': [2, 5, 4, 3, 6]  } 
df = pd.DataFrame(data)
df

Name Department  Salary  Experience
0  Rafiq         HR   40000           2
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
3   Rima      Sales   45000           3
4  Faruk      Sales   47000           6

In [66]:
d = df[df['Salary']>45000]
d

Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6

In [67]:
df.loc[df['Department']=='IT']

Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4

In [68]:
df.sort_values('Experience')

Name Department  Salary  Experience
0  Rafiq         HR   40000           2
3   Rima      Sales   45000           3
2  Tuhin         IT   52000           4
1  Nadia         IT   55000           5
4  Faruk      Sales   47000           6

In [69]:
data = {    'City': ['Dhaka', 'Sylhet', 'Chittagong', 'Rajshahi', 'Khulna'],    'Temp': [32, 28, 30, 35, 33],    'Humidity': [60, 75, 70, 55, 65]  } ;df = pd.DataFrame(data);df

City  Temp  Humidity
0       Dhaka    32        60
1      Sylhet    28        75
2  Chittagong    30        70
3    Rajshahi    35        55
4      Khulna    33        65

In [70]:
d = df.loc[df['Humidity']>33]
d.sort_values('Humidity')

City  Temp  Humidity
3    Rajshahi    35        55
0       Dhaka    32        60
4      Khulna    33        65
2  Chittagong    30        70
1      Sylhet    28        75

In [76]:
des = df.sort_values('Humidity',ascending=False)
des

City  Temp  Humidity
1      Sylhet    28        75
2  Chittagong    30        70
4      Khulna    33        65
0       Dhaka    32        60
3    Rajshahi    35        55

In [77]:
des.loc[:,'Humidity'].head(1)

1    75
Name: Humidity, dtype: int64